---
driver:
  name: digitalocean

provisioner:
  name: chef_zero

platforms:
  - name: centos-6-5-x64
  - name: coreos-stable

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
